### ISSUE TITLE
Implement subscription grouping and sorting

### ISSUE THREAD

**Issue by GoogleCodeExporter** [benfortuna/newsagent#7]
```
Grouping:

 - Date: Today, Yesterday, Older Items
 - Domain: .org, .edu, .com, etc
 - Frequency: < 10 posts today, this week, this month

Sorting:

 - Date
 - Title
 - Domain

```

Original issue reported on code.google.com by `benfortuna` on 9 Feb 2012 at 4:33
